### PR TITLE
fix: fix Linux package scripts

### LINKED ISSUE #799: Systemd service stopped and disabled after rpm package update
I recently updated our otelcol-contrib rpm package from version 0.112.0 to 0.117.0 and noticed that after the update the otelcol-contrib systemd service was stopped and disabled.

As you can see in https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#ordering, is first executed the **postinstall** (post) of the previous package version (4.) and then the **preuninstall** (preun) of the new package version (9.).

In the here generated rpm package is first the otelcol-contrib service enabled and started in the **postinstall** of the previous version, and then stopped and disabled in the **preuninstall** of the new version.

The deb package seams to be not affected, because regarding https://wiki.debian.org/MaintainerScripts#Upgrading is there first executed the **preuninstall** (prerm) of the previous version and then the **postinstall** (postinst) of the new version.

I will later create a PR for this.

### PR DESCRIPTION
**Pull request by netsandbox**
fixes #799

### CODE REVIEW

File: distributions/otelcol-otlp/preremove.sh [hunk 1]
```diff
@@ -14,7 +14,9 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-if command -v systemctl >/dev/null 2>&1; then
-    systemctl stop otelcol-otlp.service
-    systemctl disable otelcol-otlp.service
+if [ "$1" != "1" ]; then
```
Comment (atoulme) [inline distributions/otelcol-otlp/preremove.sh:17]: What does this check on?

**Comment by atoulme** [comment]
Please include a changelog. Any way to test those changes?

**Comment by netsandbox** [comment]
I have now added a changelog.

If the build rpm package works can be tested on a RHEL based OS host.

Actually the main fix from this MR, that the service is stopped and disabled after a rpm package update, can't be tested now, because when you install a package release with the fix from this MR, the package **preuninstall** script from the **previous** release will still stop and disable the service (see details on this in the linked issue #799).
You will only see if this works when you install a release, after the release with this MR fix.

**Comment by atoulme** [comment]
Makes sense, that's an unhappy confluence of events, we should ideally add tests to test lifecycle after this release.

**Comment by netsandbox** [comment]
I was also a little surprised that no one else ever noticed this since now.

It would make sense to create a release after this MR is merged, to get a fixed version out as soon as possible

**Review by atoulme — APPROVED** [review]

**Review by MovieStoreGuy — APPROVED** [review]

**Review by mowies — COMMENTED** [review]
will your changes also work with the .deb package for debian based systems?
the shell scripts are also used for that package

**Comment by netsandbox** [comment]
> will your changes also work with the .deb package for debian based systems? the shell scripts are also used for that package

Yes, the changes work also for the Debian packages.
As the Debian packages use a different script order, they are not affected by this problem.

We just don't run the service stop and disable when `$1` is `1`, and this is only the case if the rpm package is upgraded. Debian package install never provides `1` for `$1` to a prerm script, see https://wiki.debian.org/MaintainerScripts

**Review by mowies — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
